# Generated by Django 5.2.16 on 2026-08-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_phase1_5_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionline',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
