# Generated by Django 5.2.16 on 2026-08-04 01:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_phase1_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('order', 'Order'), ('stock', 'Stock'), ('both', 'Both')], default='order', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('locked', 'Locked')], db_index=True, default='draft', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('area', models.ForeignKey(blank=True, help_text='Null = all areas (items by default_area / par presence).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walks', to='catalog.storagearea')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_qty', models.DecimalField(blank=True, decimal_places=6, help_text='As entered. Null when skipped (B3). 0 = empty shelf.', max_digits=18, null=True)),
                ('counted_unit', models.CharField(blank=True, default='', max_length=32)),
                ('qty_base', models.DecimalField(blank=True, decimal_places=6, help_text='counted_qty converted to item base unit.', max_digits=18, null=True)),
                ('proposed_order_qty', models.DecimalField(blank=True, decimal_places=6, help_text='System shortfall snapshot (base units); never binding.', max_digits=18, null=True)),
                ('planned_order_qty', models.DecimalField(blank=True, decimal_places=6, help_text="Mykola's order qty (base units); the only binding number.", max_digits=18, null=True)),
                ('theoretical_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('variance_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('skipped', models.BooleanField(default=False, help_text='True when blank count — skip ≠ 0.')),
                ('note', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walk_lines', to='catalog.storagearea')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='walk_lines', to='catalog.item')),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='walks.walk')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('walk', 'item', 'area'), name='uniq_walkline_walk_item_area', nulls_distinct=False)],
            },
        ),
    ]
