# Generated by Django 5.2.16 on 2026-08-03 18:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_phase1_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('occupancy_rooms', models.PositiveIntegerField(blank=True, null=True)),
                ('occupancy_guests', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'service days',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='DishTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('breakfast_buffet', 'Breakfast buffet'), ('a_la_carte', 'A la carte'), ('banquet_buffet', 'Banquet buffet'), ('banqueting', 'Banqueting'), ('canteen', 'Canteen'), ('skybar', 'Skybar')], db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('produce', 'Produce'), ('replenish', 'Replenish'), ('check', 'Check')], default='check', max_length=16)),
                ('kind', models.CharField(choices=[('dish', 'Dish'), ('sauce', 'Sauce'), ('prep', 'Prep'), ('stock', 'Stock'), ('buffet', 'Buffet'), ('service', 'Service')], default='dish', max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('unit', models.CharField(blank=True, default='ea', max_length=16)),
                ('par_level', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('supports_lounge', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='False = off-menu; keep template + items, skip board generation.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_templates', to='catalog.item')),
            ],
            options={
                'ordering': ['section', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DishTemplateComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Display name when item FK missing.', max_length=255)),
                ('planned_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, default='ea', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dish_template_components', to='catalog.item')),
                ('supplier_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.supplieritem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='planning.dishtemplate')),
            ],
            options={
                'ordering': ['template_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('produce', 'Produce'), ('replenish', 'Replenish'), ('check', 'Check')], db_index=True, max_length=16)),
                ('kind', models.CharField(choices=[('dish', 'Dish'), ('sauce', 'Sauce'), ('prep', 'Prep'), ('stock', 'Stock'), ('buffet', 'Buffet'), ('service', 'Service')], default='dish', max_length=16)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('unit', models.CharField(blank=True, default='ea', max_length=16)),
                ('proposed_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('planned_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=6, help_text='Null for mode=check (explicit: no progress bar).', max_digits=18, null=True)),
                ('par_level', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('prep', 'Prep'), ('ready', 'Ready'), ('served', 'Served'), ('held', 'Held'), ('eighty_six', '86')], db_index=True, default='planned', max_length=16)),
                ('supports_lounge', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('menu', 'Menu'), ('template', 'Template'), ('manual', 'Manual'), ('assist', 'Assist')], default='manual', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, help_text='Nullable — quick-add and partial catalogue OK.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_lines', to='catalog.item')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='planning.dishtemplate')),
            ],
            options={
                'ordering': ['service_section_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='planning.productionline')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LineComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('planned_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, default='ea', max_length=16)),
                ('done', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.item')),
                ('supplier_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.supplieritem')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='planning.productionline')),
            ],
            options={
                'ordering': ['line_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('breakfast_buffet', 'Breakfast buffet'), ('a_la_carte', 'A la carte'), ('banquet_buffet', 'Banquet buffet'), ('banqueting', 'Banqueting'), ('canteen', 'Canteen'), ('skybar', 'Skybar')], db_index=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('covers', models.PositiveIntegerField(blank=True, null=True)),
                ('covers_source', models.CharField(blank=True, choices=[('occupancy', 'Occupancy'), ('booked', 'Booked'), ('beo', 'BEO'), ('forecast', 'Forecast'), ('manual', 'Manual')], default='', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('service_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='planning.serviceday')),
            ],
            options={
                'ordering': ['service_day_id', 'section'],
            },
        ),
        migrations.AddField(
            model_name='productionline',
            name='service_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='planning.servicesection'),
        ),
        migrations.AddConstraint(
            model_name='dishtemplate',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='uniq_dishtemplate_section_name'),
        ),
        migrations.AddConstraint(
            model_name='servicesection',
            constraint=models.UniqueConstraint(fields=('service_day', 'section'), name='uniq_servicesection_day_section'),
        ),
        migrations.AddConstraint(
            model_name='productionline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_qty__isnull', True), ('mode', 'check')), models.Q(('mode', 'check'), _negated=True), _connector='OR'), name='productionline_check_actual_null'),
        ),
    ]
