# Generated by Django 5.2.16 on 2026-08-04 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_d12_notes_house_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishtemplate',
            name='yield_per_cover',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional per-cover yield for produce scaling (banquet*). Null = no auto proposed_qty.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='serviceday',
            name='outturn',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='beo_events',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='outturn',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('serve_at', models.TimeField(blank=True, null=True)),
                ('covers', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='planning.servicesection')),
            ],
            options={
                'ordering': ['service_section_id', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wave_allocations', to='planning.productionline')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='planning.wave')),
            ],
            options={
                'ordering': ['line_id', 'wave_id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet', models.CharField(choices=[('executive_lounge', 'Executive lounge')], db_index=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('covers', models.PositiveIntegerField(blank=True, null=True)),
                ('service_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='planning.servicesection')),
            ],
            options={
                'ordering': ['service_section_id', 'outlet'],
                'constraints': [models.UniqueConstraint(fields=('service_section', 'outlet'), name='uniq_serviceoutlet_section_outlet')],
            },
        ),
        migrations.AddConstraint(
            model_name='wave',
            constraint=models.UniqueConstraint(fields=('service_section', 'name'), name='uniq_wave_section_name'),
        ),
        migrations.AddConstraint(
            model_name='waveallocation',
            constraint=models.UniqueConstraint(fields=('line', 'wave'), name='uniq_waveallocation_line_wave'),
        ),
    ]
