# Generated by Django 5.2.16 on 2026-08-04 03:39
# B10: append-only StockMovement — app save() guard + PG BEFORE UPDATE OR DELETE trigger.

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


FORWARD_TRIGGER = """
CREATE OR REPLACE FUNCTION inventory_stockmovement_append_only()
RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'StockMovement is append-only (B10): UPDATE/DELETE blocked';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_inventory_stockmovement_append_only ON inventory_stockmovement;
CREATE TRIGGER trg_inventory_stockmovement_append_only
  BEFORE UPDATE OR DELETE ON inventory_stockmovement
  FOR EACH ROW
  EXECUTE FUNCTION inventory_stockmovement_append_only();
"""

REVERSE_TRIGGER = """
DROP TRIGGER IF EXISTS trg_inventory_stockmovement_append_only ON inventory_stockmovement;
DROP FUNCTION IF EXISTS inventory_stockmovement_append_only();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_d12_notes_house_made'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=18)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='catalog.storagearea')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='catalog.item')),
            ],
            options={
                'ordering': ['item_id', 'area_id'],
                'constraints': [models.UniqueConstraint(fields=('item', 'area'), name='uniq_stockbalance_item_area')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=6, help_text='SIGNED base-unit delta. Receipt/yield/transfer_in usually +; waste/consume/transfer_out usually −; count_adjustment either sign.', max_digits=18)),
                ('kind', models.CharField(choices=[('receipt', 'Receipt'), ('consume', 'Consume'), ('yield', 'Yield'), ('waste', 'Waste'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out'), ('count_adjustment', 'Count adjustment')], db_index=True, max_length=32)),
                ('source_type', models.CharField(blank=True, db_index=True, default='', help_text='e.g. delivery, walk, api_waste, api_count_adjustment, transfer', max_length=64)),
                ('source_id', models.CharField(blank=True, db_index=True, default='', help_text='Stringified source pk or composite key for idempotency.', max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.storagearea')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.item')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['item', 'area', '-occurred_at'], name='inventory_s_item_id_ba6543_idx'), models.Index(fields=['source_type', 'source_id'], name='inventory_s_source__18ec1c_idx')],
            },
        ),
        migrations.RunSQL(sql=FORWARD_TRIGGER, reverse_sql=REVERSE_TRIGGER),
    ]
