# Generated by Django 5.2.16 on 2026-08-04 01:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_phase1_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_packs', models.DecimalField(blank=True, decimal_places=6, help_text='System ceil(shortfall/pack_qty); never binding.', max_digits=18, null=True)),
                ('packs', models.DecimalField(blank=True, decimal_places=6, help_text="Mykola's packs (defaults to proposed).", max_digits=18, null=True)),
                ('qty_base', models.DecimalField(blank=True, decimal_places=6, help_text='packs * pack_qty in item base units.', max_digits=18, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('par', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('counted', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('on_order', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('shortfall', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('complete', 'Complete')], db_index=True, default='open', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='catalog.supplier')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packs_expected', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('packs_received', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, choices=[('short', 'Short'), ('over', 'Over'), ('substituted', 'Substituted'), ('rejected', 'Rejected'), ('ok', 'OK')], default='', help_text='short|over|substituted|rejected|ok', max_length=16)),
                ('note_text', models.TextField(blank=True, default='')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.delivery')),
                ('supplier_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='catalog.supplieritem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('received', 'Received'), ('closed', 'Closed')], db_index=True, default='draft', max_length=16)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='catalog.supplier')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
    ]
