# Generated by Django 5.2.16 on 2026-08-04 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_phase1_catalogue'),
        ('purchasing', '0001_phase2_walk_purchasing'),
        ('walks', '0001_phase2_walk_purchasing'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='walk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='walks.walk'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='supplier_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='catalog.supplieritem'),
        ),
        migrations.AddConstraint(
            model_name='deliveryline',
            constraint=models.UniqueConstraint(fields=('delivery', 'supplier_item'), name='uniq_deliveryline_delivery_supplier_item'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'supplier_item'), name='uniq_poline_po_supplier_item'),
        ),
    ]
