# Generated by Django 5.2.16 on 2026-08-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_phase2_walk_purchasing'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='scope',
            field=models.CharField(choices=[('replenishment', 'Replenishment'), ('event', 'Event')], db_index=True, default='replenishment', help_text='replenishment (default): standing top-up; counts toward on_order. event: banquet/one-off; never reduces replenishment shortfall.', max_length=16),
        ),
    ]
