# Generated by Django 5.2.16 on 2026-08-03 17:17

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogIngestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_kind', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('csv', 'CSV')], default='text', max_length=16)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('image', models.FileField(blank=True, null=True, upload_to='catalog_ingest/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('review', 'Ready for review'), ('failed', 'Failed'), ('done', 'Done')], db_index=True, default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('q_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('walkin', 'Walk-in'), ('freezer', 'Freezer'), ('dry', 'Dry'), ('bar', 'Bar'), ('section', 'Section')], max_length=16)),
                ('walk_order', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('walk_order'), nulls_last=True), 'name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('account_code', models.CharField(blank=True, default='', max_length=64)),
                ('order_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='ISO weekday ints 0=Mon .. 6=Sun (empty = unknown).', size=None)),
                ('cutoff_time', models.TimeField(blank=True, null=True)),
                ('lead_time_days', models.PositiveSmallIntegerField(default=1)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', help_text='Optional internal code. Name+unit is enough to exist.', max_length=64)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('base_unit', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('ea', 'ea')], default='ea', max_length=4)),
                ('category', models.CharField(blank=True, default='', max_length=128)),
                ('walk_order', models.PositiveIntegerField(blank=True, null=True)),
                ('allergens', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
                ('active', models.BooleanField(default=True)),
                ('unverified', models.BooleanField(default=False, help_text='True when source notes say verify/uncertain — never silent.')),
                ('notes', models.TextField(blank=True, default='')),
                ('default_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_items', to='catalog.storagearea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, default='', max_length=128)),
                ('pack_description', models.CharField(blank=True, default='', max_length=255)),
                ('pack_qty', models.DecimalField(blank=True, decimal_places=6, help_text='Pack size in item base units. Null until known — never invent.', max_digits=18, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, help_text='Nullable. Prices last; never invent.', max_digits=12, null=True)),
                ('preferred', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('unverified', models.BooleanField(default=False, help_text='True when code/supplier from sheet needs verify.')),
                ('notes', models.TextField(blank=True, default='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_items', to='catalog.item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_items', to='catalog.supplier')),
            ],
            options={
                'ordering': ['supplier_id', 'item_id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogIngestProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('base_unit', models.CharField(blank=True, default='ea', max_length=4)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=128)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=128)),
                ('pack_description', models.CharField(blank=True, default='', max_length=255)),
                ('pack_qty', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('flagged_low_confidence', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='catalog.catalogingestupload')),
                ('result_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.item')),
                ('result_supplier_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.supplieritem')),
            ],
            options={
                'ordering': ['upload_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=32)),
                ('factor_to_base', models.DecimalField(decimal_places=6, help_text='Multiply pack qty by this to get base units (g|ml|ea).', max_digits=18)),
                ('countable', models.BooleanField(default=True, help_text='False for continuous measures that are not pack-counted.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='catalog.item')),
            ],
            options={
                'ordering': ['item_id', 'unit'],
            },
        ),
        migrations.CreateModel(
            name='ParLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField(blank=True, help_text='0=Mon .. 6=Sun; null = all-days default.', null=True)),
                ('qty', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Par quantity in item base units.', max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_levels', to='catalog.item')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='par_levels', to='catalog.storagearea')),
            ],
            options={
                'ordering': ['item_id', 'area_id', 'weekday'],
                'constraints': [models.UniqueConstraint(fields=('item', 'area', 'weekday'), name='uniq_parlevel_item_area_weekday', nulls_distinct=False), models.CheckConstraint(condition=models.Q(('weekday__isnull', True), models.Q(('weekday__gte', 0), ('weekday__lte', 6)), _connector='OR'), name='parlevel_weekday_range')],
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('base_unit__in', ['g', 'ml', 'ea'])), name='item_base_unit_g_ml_ea'),
        ),
        migrations.AddConstraint(
            model_name='supplieritem',
            constraint=models.UniqueConstraint(fields=('supplier', 'item'), name='uniq_supplieritem_supplier_item'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('item', 'unit'), name='uniq_unitconversion_item_unit'),
        ),
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.CheckConstraint(condition=models.Q(('factor_to_base', 0), _negated=True), name='unitconversion_factor_nonzero'),
        ),
    ]
