# Generated by Django 5.2.16 on 2026-08-04 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_phase1_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='house_made',
            field=models.BooleanField(default=False, help_text='True when prep is made in-house (recipe-lite via ItemComponent). Not a replacement for bought SupplierItems.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='ItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(blank=True, decimal_places=6, help_text='Rough qty in component base units when known; null = unverified/unknown.', max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, default='', help_text='Prefer component base_unit when set.', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in', to='catalog.item')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.item')),
            ],
            options={
                'ordering': ['parent_id', 'sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'component'), name='uniq_itemcomponent_parent_component'), models.CheckConstraint(condition=models.Q(('parent', models.F('component')), _negated=True), name='itemcomponent_no_self_ref')],
            },
        ),
    ]
