# Generated by Django 5.2.16 on 2026-08-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_phase2_walk_purchasing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkline',
            name='theoretical_qty',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Theoretical on-hand from ledger balance at submit/lock (0 if none).', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='walkline',
            name='variance_qty',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Unexplained gap (counted − theoretical) after noise floor; never labelled error; never auto-corrects pars/balances.', max_digits=18, null=True),
        ),
    ]
